# Site settings
title: Fit for E-Commerce
header-img: img/2017-04-07-webshops-screenshots/webshop-header.jpg
email: fitforecommerce@kbs-bth.de
copyright_name: Fit for E-Commerce project team / Martin Kolb
description: "Teaching vocational students e-commerce skills. The website for the Erasmus+ funded strategic partnership."
baseurl: ""
url: "https://fitforecommerce.github.io"
# twitter_username: ---
github_username:  fitforecommerce
# facebook_username:  ---
# email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "deploy", "Gemfile", "Gemfile.lock"]

gems: [jekyll-paginate, jekyll-feed]
